import 'package:falci_kedi/view_items/abstruct/base_fal_service.dart';

class LifeFal extends BaseFalService {
  @override
  List<String> get myFals => [
        'Arkandan laf eden bir insan, sen hiçbir şey yapmasan bile bir yerden bir sorun yaşayacak. Karma işte tam olarak böyle bir şey. Sen ise sadece tüm bu olanları izleyeceksin. Bununla birlikte, zamanında görüşmeyi kestiğin bir insan seninle tekrar iletişime geçmeye çalışabilir. Zamanında susmayı tercih ettiğinden ve için içini kemirdiğinden dolayı ona diyeceğin lafları güzel hazırlasan iyi edersin. İçinde kalmasından çok daha iyidir sonuçta değil mi sevgili okurum? Yarın görüşmek üzere, kendine iyi bak! ',
        'Alacağın iyi bir haber günün ilk saatlerinden itibaren enerjini oldukça yükseltecek diyebilirim. Bu durum da sana aradığın o motivasyonu verecek. Günün oldukça güzel geçecek anlayacağın. Tadını çıkar :) Bununla birlikte, tüm maddi sorunlarının birden üzerine yıkıldığını düşünmeye başlamış ve kendini çok sıkmışsın. Biraz daha dikkatli ve sabırlı davranman gerekiyor. Yakında bir iş teklifi alacaksın, bu fırsatı güzel bir şekilde değerlendirmeni istiyorum senden. Güzel günler pek yakın! Yarın görüşmek üzere, kendine iyi bak!',
        'Arkadaşlarından biri ile yapacağın bir görüşme sana çok iyi gelecek ancak sen hiçbir şey yapmak istemiyorsun. Bu nedenle kendini biraz zorlaman ve yaşam alanından çıkarak biraz da olsa sosyalleşmen gerekiyor. Bu şekilde nereye kadar değil mi? Artık bu duvarlarını yıkman ve bir adım atman gerekiyor :) Bununla birlikte, sağlık konularında kendini bu dönem çok boşlamışsın. Bu da sana sorun olarak dönebilir. Kendini biraz daha önemsemen gereken günlere giriyorsun, dikkatli olmanda fayda var. Aksi takdirde sonrasında pişman olacaksın benden söylemesi. Yarın görüşmek üzere, kendine iyi bak!',
        'Bugün elinden hiçbir şey gelmeyen sorunlarla karşılaşabilirsin. Bu nedenle de kendine çok fazla yüklenmemen gerekiyor. Sadece sabırlı olman ve bir şeyleri de zaman bırakman gerekiyor. İnan bana, her şey yoluna girecek. Bununla birlikte, yeniliklere açık olduğun bir dönemdesin ve bunu da iyi değerlendirmen gerekiyor. Artık hayatını kendin için yaşamaya başlamalısın. Hepimizin bu hayatta birtakım hayalleri var ve bu hayaller gerçekleşmesi için bizleri bekliyor sevgili okuyucum :) Yarın görüşmek üzere, kendine iyi bak!',
        'Çevrendeki insanları tek tek elemeye başlamışsın ve bu durumdan da oldukça memnunsun. Çünkü, sen artık çevrende yalan dostluklar istemiyorsun. Çok da iyi yapıyorsun. Hayatında bu tarz insanların oluşu sadece sana zarar verir, bunu unutmaman gerekiyor. Bununla birlikte, bulunduğun bir ortamda istemediğin bir tartışmaya girebilirsin. Bu da senin enerjini düşürebilir. Bundan uzak durmaya ve sadece kendine odaklanmaya başlaman gerekiyor. Hayatında bu tarz gereksiz diyaloglara hiç yer olmamalı. Yarın görüşmek üzere, kendine iyi bak! ',
        'Çevrende güçlü bir kadın var ve bu kadın seni olduğun yerden çok daha yukarılara taşımak istiyor. Sana çok değer veren bu kadın ile uzun bir görüşmeniz olacak. Bu kişinin adında D harfi olduğunu da söylemem gerekiyor. Bununla birlikte, dış görünüşün ile ilgili değişiklikler düşünüyorsun ancak çok cesaret edemiyorsun. Bugün değişiklikler için oldukça verimli bir gün olacak diyebilirim. Değişim birçok insana iyi gelir, eminim sana da çok iyi gelecek. Bana güven  Yarın görüşmek üzere, kendine iyi bak! ',
        'Yakın çevrende seninle çok iyi gibi davranan ancak her konuda eksiklerini başkalarına anlatan biri var. Bu insana sen çok güvensen de bugün yaşanacak bir olay ile gerçekleri görebileceksin. Bu olayı yaşadığın için sevinmelisin bence, bu sayede gerçekleri çok daha hızlı ve net bir şekilde görebileceksin. Bununla birlikte, arkadaşlarından biri ile uzun bir konuşma yapabilirsin. Bu konuşma ile aslında ortak düşünceler içinde olduğunuzu göreceksin ve bu durum sizi birbirine bağlayacak. Yarın görüşmek üzere, kendine iyi bak!',
        'Maddi olarak zorlanmaktan artık yorulmuşsun gibi geldi bana. Eline geçecek paraları iyi değerlendirmen gerekiyor. Tüm zamanların en yoğun dönemlerinden birine gireceksin ve bu nedenle de kendini hazırlamalısın. Tüm bu yorucu döneme rağmen, emeklerinin karşılığını en iyi şekilde alacağın bir döneme giriyorsun. Bununla birlikte, ailen ile çok fazla vakit geçirememişsin ve bu da seni haliyle üzmüş. Onlara da vakit ayırman gerektiğinin farkındasın. Onlarla yapacağın ufak bir görüşme hepinize iyi gelebilir. Onların kıymetini bilmen gerekiyor. Yarın görüşmek üzere, kendine iyi bak!',
        'Geçtiğimiz günlerde arkadaş ortamından biriyle ufak bir tartışma yaşamışsın. Bu tartışma da seni fazlasıyla yormuş. Artık böyle kaosların içine girmek istemiyorsun ve bugün de bunu çok net belli edeceksin. Bazı insanlar kaostan beslenir fakat sen onlardan biri değilsin. Bununla birlikte, tüm zamanların en yoğun haftalarından birini geçirmişsin. Artık bugün kafanı dinlemek ve tamamen kendini vakit ayırmak istiyorsun. Senden biraz daha sabırlı olmanı istiyorum. İnan bana, yaşanacak çok güzel günler seni bekliyor! Yarın görüşmek üzere, kendine iyi bak!',
        'Bu dönem oldukça bunalmışsın. İçinden hiçbir şey yapmak gelmiyor ve sen de bu durumdan son derece rahatsızsın. O zaman harekete geçmeye ne dersin? Hadi hemen bir yürüyüşe çık ve kendin için ilk adımını at :) Bununla birlikte, tüm maddi sorunlarını çözebilmek için eline bir fırsat geçebilir. Kendini maddi olarak çok zorlamışsın ve bu durum seni yormaya başlamış. Bunları çözmek için de elinden geleni yapacaksın. Aşk hayatında da gelişmelerin seni beklediğini söylemeliyim. Yarın görüşmek üzere, kendine iyi bak!',
        'Bugün, alacağın kararları sorgulayacağın bir gün olacak diyebilirim. Bu kararları yakınlarından biriyle konuşmak isteyebilirsin. Bu da en doğru kararlardan biri olacak diyebilirim. Bazen bizim göremediğimiz bir açıyı yakınlarımız görebiliyor. Bununla birlikte, çevrendeki diğer insanların da gerçek yüzünü göreceksin ve artık onlarla arandaki bağları sorgulayacaksın. Hayatında sadece sana değer veren insanları bırakman bence çok iyi bir fikir, ne dersin? :) Yarın görüşmek üzere, kendine iyi bak!'
      ];
}
